name: Build

on:
  push:
    branches:
      - main

jobs:
  build-mac-windows:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    if: ${{ github.repository_owner == 'lacymorrow' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Install Node and NPM
        uses: actions/setup-node@v4

      - name: Install and build
        run: |
          npm install
          npm run dist-mac

      # - name: Archive build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: release
      #     path: |
      #       release/build
      #       !release/**/builder*
      #       !release/**/linux*
      #       !release/**/mac*
      #       !release/**/win*
